# Generated by Django 5.2.7 on 2025-10-04 18:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="שם תבנית")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="תבנית ברירת מחדל"),
                ),
                (
                    "header_text",
                    models.TextField(blank=True, null=True, verbose_name="טקסט כותרת"),
                ),
                (
                    "footer_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="טקסט כותרת תחתונה"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=200, verbose_name="שם החברה"),
                ),
                ("company_address", models.TextField(verbose_name="כתובת החברה")),
                (
                    "company_phone",
                    models.CharField(max_length=20, verbose_name="טלפון החברה"),
                ),
                (
                    "company_email",
                    models.EmailField(max_length=254, verbose_name="אימייל החברה"),
                ),
                (
                    "company_tax_id",
                    models.CharField(max_length=20, verbose_name="ח.פ החברה"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="invoice_logos/",
                        verbose_name="לוגו",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="פעיל")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "תבנית חשבונית",
                "verbose_name_plural": "תבניות חשבוניות",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="שם מיקום"
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[("store", "חנות"), ("warehouse", "מחסן")],
                        default="store",
                        max_length=20,
                        verbose_name="סוג מיקום",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="תיאור")),
                ("address", models.TextField(blank=True, verbose_name="כתובת")),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="עיר"),
                ),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=10, verbose_name="מיקוד"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="טלפון"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="אימייל"
                    ),
                ),
                (
                    "manager_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="שם מנהל"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="קיבולת (יחידות)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="פעיל")),
                (
                    "is_main_warehouse",
                    models.BooleanField(default=False, verbose_name="מחסן ראשי"),
                ),
                (
                    "is_main_store",
                    models.BooleanField(default=False, verbose_name="חנות ראשית"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "מיקום",
                "verbose_name_plural": "מיקומים",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("contact_person", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=200, verbose_name="שם החברה"),
                ),
                (
                    "business_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="מספר עוסק מורשה"
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(blank=True, max_length=20, verbose_name="ח.פ"),
                ),
                ("address", models.CharField(max_length=200, verbose_name="כתובת")),
                ("city", models.CharField(max_length=100, verbose_name="עיר")),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=10, verbose_name="מיקוד"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="טלפון")),
                ("email", models.EmailField(max_length=254, verbose_name="אימייל")),
                ("website", models.URLField(blank=True, verbose_name="אתר אינטרנט")),
                (
                    "invoice_prefix",
                    models.CharField(
                        default="INV", max_length=10, verbose_name="קידומת חשבונית"
                    ),
                ),
                (
                    "current_invoice_number",
                    models.PositiveIntegerField(
                        default=1, verbose_name="מספר חשבונית נוכחי"
                    ),
                ),
                (
                    "tax_authority_allocation_number",
                    models.CharField(
                        blank=True,
                        help_text="נדרש לחשבוניות מעל 20,000 ₪",
                        max_length=50,
                        verbose_name="מספר הקצאה מרשות המיסים",
                    ),
                ),
                (
                    "digital_signature_key",
                    models.TextField(blank=True, verbose_name="מפתח חתימה דיגיטלית"),
                ),
                (
                    "signature_certificate",
                    models.TextField(blank=True, verbose_name="תעודת חתימה"),
                ),
                (
                    "default_tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=18,
                        max_digits=5,
                        verbose_name='אחוז מע"מ ברירת מחדל',
                    ),
                ),
                (
                    "archive_years",
                    models.PositiveIntegerField(
                        default=7, verbose_name="שנות שמירה (ברירת מחדל 7)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="פעיל")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="עודכן על ידי",
                    ),
                ),
            ],
            options={
                "verbose_name": "הגדרות חברה",
                "verbose_name_plural": "הגדרות חברה",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="שם לקוח")),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("individual", "פרטי"),
                            ("business", "עסקי"),
                            ("wholesale", "סיטונאי"),
                        ],
                        default="individual",
                        max_length=20,
                        verbose_name="סוג לקוח",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "נמוכה"),
                            ("medium", "בינונית"),
                            ("high", "גבוהה"),
                            ("vip", "VIP"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="עדיפות",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="אימייל"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="טלפון"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="נייד"
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="אתר אינטרנט"),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="כתובת"),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="עיר"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="מיקוד"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="ישראל", max_length=100, verbose_name="מדינה"
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="ח.פ/ת.ז"
                    ),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="ת.ז"
                    ),
                ),
                (
                    "customer_code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="קוד לקוח",
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="מגבלת אשראי",
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        default="30 ימים", max_length=100, verbose_name="תנאי תשלום"
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="אחוז הנחה",
                    ),
                ),
                (
                    "total_purchases",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name='סה"כ רכישות',
                    ),
                ),
                (
                    "last_purchase_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="רכישה אחרונה"
                    ),
                ),
                (
                    "total_orders",
                    models.PositiveIntegerField(default=0, verbose_name='סה"כ הזמנות'),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="פעיל")),
                ("is_vip", models.BooleanField(default=False, verbose_name="לקוח VIP")),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="הערות"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="נוצר על ידי",
                    ),
                ),
            ],
            options={
                "verbose_name": "לקוח",
                "verbose_name_plural": "לקוחות",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CustomerAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("birthday", "יום הולדת"),
                            ("anniversary", "יום השנה"),
                            ("follow_up", "מעקב נדרש"),
                            ("payment_overdue", "תשלום באיחור"),
                            ("credit_limit", "מגבלת אשראי"),
                            ("inactive", "לקוח לא פעיל"),
                            ("high_value", "רכישה גבוהה"),
                        ],
                        max_length=20,
                        verbose_name="סוג התראה",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="כותרת")),
                ("message", models.TextField(verbose_name="הודעה")),
                ("is_read", models.BooleanField(default=False, verbose_name="נקרא")),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="נפתר"),
                ),
                (
                    "alert_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="תאריך התראה"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="תאריך פתרון"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_alerts",
                        to="inventory.customer",
                        verbose_name="לקוח",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="נפתר על ידי",
                    ),
                ),
            ],
            options={
                "verbose_name": "התראת לקוח",
                "verbose_name_plural": "התראות לקוחות",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("general", "כללי"),
                            ("call", "שיחה"),
                            ("email", "אימייל"),
                            ("meeting", "פגישה"),
                            ("complaint", "תלונה"),
                            ("compliment", "מחמאה"),
                            ("follow_up", "מעקב"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="סוג הערה",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="כותרת")),
                ("content", models.TextField(verbose_name="תוכן")),
                (
                    "is_important",
                    models.BooleanField(default=False, verbose_name="חשוב"),
                ),
                (
                    "follow_up_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="תאריך מעקב"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="נוצר על ידי",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_notes",
                        to="inventory.customer",
                        verbose_name="לקוח",
                    ),
                ),
            ],
            options={
                "verbose_name": "הערת לקוח",
                "verbose_name_plural": "הערות לקוחות",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transfer_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="מספר העברה"
                    ),
                ),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[
                            ("warehouse_to_store", "מחסן לחנות"),
                            ("store_to_warehouse", "חנות למחסן"),
                            ("store_to_store", "חנות לחנות"),
                            ("warehouse_to_warehouse", "מחסן למחסן"),
                        ],
                        max_length=30,
                        verbose_name="סוג העברה",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "ממתין"),
                            ("in_transit", "בדרך"),
                            ("completed", "הושלם"),
                            ("cancelled", "בוטל"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="סטטוס",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="הערות"),
                ),
                (
                    "transfer_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="תאריך העברה"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="נוצר על ידי",
                    ),
                ),
                (
                    "from_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_from",
                        to="inventory.location",
                        verbose_name="ממיקום",
                    ),
                ),
                (
                    "to_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_to",
                        to="inventory.location",
                        verbose_name="למיקום",
                    ),
                ),
            ],
            options={
                "verbose_name": "העברת מלאי",
                "verbose_name_plural": "העברות מלאי",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LocationAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("low_stock", "מלאי נמוך"),
                            ("out_of_stock", "אזל מהמלאי"),
                            ("overstock", "מלאי עודף"),
                            ("capacity_full", "קיבולת מלאה"),
                            ("capacity_almost_full", "קיבולת כמעט מלאה"),
                            ("expired_products", "מוצרים פגי תוקף"),
                            ("near_expiry", "מוצרים קרובים לפג תוקף"),
                            ("maintenance_required", "נדרש תחזוקה"),
                            ("security_breach", "הפרת אבטחה"),
                            ("temperature_issue", "בעיית טמפרטורה"),
                            ("other", "אחר"),
                        ],
                        max_length=30,
                        verbose_name="סוג התראה",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "נמוכה"),
                            ("medium", "בינונית"),
                            ("high", "גבוהה"),
                            ("critical", "קריטית"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="עדיפות",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="כותרת")),
                ("message", models.TextField(verbose_name="הודעה")),
                ("is_read", models.BooleanField(default=False, verbose_name="נקרא")),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="נפתר"),
                ),
                (
                    "alert_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="תאריך התראה"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="תאריך פתרון"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_alerts",
                        to="inventory.location",
                        verbose_name="מיקום",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="נפתר על ידי",
                    ),
                ),
            ],
            options={
                "verbose_name": "התראת מיקום",
                "verbose_name_plural": "התראות מיקום",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "quantity",
                    models.IntegerField(
                        default=0,
                        help_text='סה"כ מלאי בכל המיקומים',
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "min_quantity",
                    models.IntegerField(
                        default=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_quantity",
                    models.IntegerField(
                        default=1000,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("pcs", "יחידות"),
                            ("kg", "קילוגרם"),
                            ("g", "גרם"),
                            ("l", "ליטר"),
                            ("ml", "מיליליטר"),
                            ("m", "מטר"),
                            ("cm", "סנטימטר"),
                            ("box", "קופסה"),
                            ("pack", "חבילה"),
                        ],
                        default="pcs",
                        max_length=10,
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "margin_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("barcode", models.CharField(blank=True, max_length=50, unique=True)),
                (
                    "barcode_image",
                    models.ImageField(blank=True, null=True, upload_to="barcodes/"),
                ),
                (
                    "product_image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "פעיל"),
                            ("inactive", "לא פעיל"),
                            ("discontinued", "הופסק"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("dimensions", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="מיקום ברירת מחדל",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.location",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("low_stock", "מלאי נמוך"),
                            ("out_of_stock", "אזל מהמלאי"),
                            ("overstock", "מלאי עודף"),
                            ("expiry", "תאריך תפוגה"),
                            ("reorder", "הזמנה מחדש"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "נמוכה"),
                            ("medium", "בינונית"),
                            ("high", "גבוהה"),
                            ("critical", "קריטית"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="מספר חשבונית"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "טיוטה"),
                            ("confirmed", "מאושר"),
                            ("completed", "הושלם"),
                            ("cancelled", "בוטל"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="סטטוס",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "ממתין לתשלום"),
                            ("partial", "תשלום חלקי"),
                            ("paid", "שולם"),
                            ("refunded", "הוחזר"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="סטטוס תשלום",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name='סכום לפני מע"מ',
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=18,
                        max_digits=5,
                        verbose_name='אחוז מע"מ',
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name='סכום מע"מ',
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="סכום כולל",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="הערות"),
                ),
                (
                    "sale_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="תאריך מכירה"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "digital_signature",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="חתימה דיגיטלית"
                    ),
                ),
                ("qr_code", models.TextField(blank=True, verbose_name="QR Code")),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="בארכיון"),
                ),
                (
                    "requires_tax_authority_number",
                    models.BooleanField(default=False, verbose_name="דורש מספר הקצאה"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="נוצר על ידי",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.customer",
                        verbose_name="לקוח",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="החנות בה בוצעה המכירה",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.location",
                        verbose_name="מיקום מכירה",
                    ),
                ),
            ],
            options={
                "verbose_name": "מכירה",
                "verbose_name_plural": "מכירות",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerSaleHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sale_date", models.DateTimeField(verbose_name="תאריך מכירה")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="סכום כולל"
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "ממתין לתשלום"),
                            ("partial", "תשלום חלקי"),
                            ("paid", "שולם"),
                            ("refunded", "הוחזר"),
                        ],
                        max_length=20,
                        verbose_name="סטטוס תשלום",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_history",
                        to="inventory.customer",
                        verbose_name="לקוח",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.sale",
                        verbose_name="מכירה",
                    ),
                ),
            ],
            options={
                "verbose_name": "היסטוריית מכירות",
                "verbose_name_plural": "היסטוריית מכירות",
                "ordering": ["-sale_date"],
            },
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="כמות",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="מחיר יחידה"
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="אחוז הנחה",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="סכום הנחה",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="סכום כולל"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                        verbose_name="מוצר",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.sale",
                        verbose_name="מכירה",
                    ),
                ),
            ],
            options={
                "verbose_name": "פריט חשבונית",
                "verbose_name_plural": "פריטי חשבונית",
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("in", "כניסה"),
                            ("out", "יציאה"),
                            ("adjustment", "תיקון"),
                            ("transfer", "העברה"),
                            ("return", "החזרה"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("previous_quantity", models.IntegerField()),
                ("new_quantity", models.IntegerField()),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransferItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="כמות",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="הערות"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                        verbose_name="מוצר",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.inventorytransfer",
                        verbose_name="העברה",
                    ),
                ),
            ],
            options={
                "verbose_name": "פריט העברה",
                "verbose_name_plural": "פריטי העברה",
            },
        ),
        migrations.CreateModel(
            name="ProductLocationStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="כמות במלאי",
                    ),
                ),
                (
                    "min_quantity",
                    models.IntegerField(
                        default=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="כמות מינימלית",
                    ),
                ),
                (
                    "last_restocked",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="תאריך אספקה אחרון"
                    ),
                ),
                (
                    "last_sold",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="תאריך מכירה אחרון"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_stocks",
                        to="inventory.location",
                        verbose_name="מיקום",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_stocks",
                        to="inventory.product",
                        verbose_name="מוצר",
                    ),
                ),
            ],
            options={
                "verbose_name": "מלאי מוצר במיקום",
                "verbose_name_plural": "מלאי מוצרים במיקומים",
                "ordering": ["product__name", "location__name"],
                "unique_together": {("product", "location")},
            },
        ),
        migrations.CreateModel(
            name="InvoiceAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "יצירה"),
                            ("view", "צפייה"),
                            ("edit", "עריכה"),
                            ("delete", "מחיקה"),
                            ("print", "הדפסה"),
                            ("email", "שליחה באימייל"),
                            ("export", "ייצוא"),
                            ("cancel", "ביטול"),
                        ],
                        max_length=20,
                        verbose_name="פעולה",
                    ),
                ),
                (
                    "performed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="זמן ביצוע"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="כתובת IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="User Agent"
                    ),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True, null=True, verbose_name="ערכים קודמים"
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(blank=True, null=True, verbose_name="ערכים חדשים"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="הערות")),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="בוצע על ידי",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="inventory.sale",
                        verbose_name="חשבונית",
                    ),
                ),
            ],
            options={
                "verbose_name": "רישום ביקורת",
                "verbose_name_plural": "רישומי ביקורת",
                "ordering": ["-performed_at"],
                "indexes": [
                    models.Index(
                        fields=["-performed_at"], name="inventory_i_perform_72fdbb_idx"
                    ),
                    models.Index(
                        fields=["sale", "-performed_at"],
                        name="inventory_i_sale_id_5db9a8_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InvoiceArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_data", models.JSONField(verbose_name="נתוני חשבונית מלאים")),
                ("invoice_html", models.TextField(verbose_name="HTML של החשבונית")),
                (
                    "invoice_pdf",
                    models.BinaryField(
                        blank=True, null=True, verbose_name="PDF של החשבונית"
                    ),
                ),
                (
                    "digital_signature",
                    models.CharField(max_length=255, verbose_name="חתימה דיגיטלית"),
                ),
                (
                    "signature_timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="זמן חתימה"),
                ),
                ("qr_code_data", models.TextField(verbose_name="נתוני QR Code")),
                (
                    "archived_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="תאריך ארכוב"),
                ),
                ("delete_after", models.DateField(verbose_name="מחיקה לאחר")),
                (
                    "is_encrypted",
                    models.BooleanField(default=False, verbose_name="מוצפן"),
                ),
                (
                    "encryption_method",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="שיטת הצפנה"
                    ),
                ),
                (
                    "sale",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.sale",
                        verbose_name="חשבונית",
                    ),
                ),
            ],
            options={
                "verbose_name": "ארכיון חשבונית",
                "verbose_name_plural": "ארכיון חשבוניות",
                "ordering": ["-archived_at"],
                "indexes": [
                    models.Index(
                        fields=["delete_after"], name="inventory_i_delete__93b2f1_idx"
                    ),
                    models.Index(
                        fields=["-archived_at"], name="inventory_i_archive_6d19e8_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="inventory_p_sku_f85905_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["barcode"], name="inventory_p_barcode_3a77e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category"], name="inventory_p_categor_607069_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["supplier"], name="inventory_p_supplie_81b183_idx"
            ),
        ),
    ]
