# Generated by Django 5.2.7 on 2025-10-04 09:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="שם לקוח")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="אימייל"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="טלפון"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="כתובת"),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="ח.פ/ת.ז"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="פעיל")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "לקוח",
                "verbose_name_plural": "לקוחות",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InventoryTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transfer_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="מספר העברה"
                    ),
                ),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[
                            ("warehouse_to_store", "מחסן לחנות"),
                            ("store_to_warehouse", "חנות למחסן"),
                            ("store_to_store", "חנות לחנות"),
                            ("warehouse_to_warehouse", "מחסן למחסן"),
                        ],
                        max_length=30,
                        verbose_name="סוג העברה",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "ממתין"),
                            ("in_transit", "בדרך"),
                            ("completed", "הושלם"),
                            ("cancelled", "בוטל"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="סטטוס",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="הערות"),
                ),
                (
                    "transfer_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="תאריך העברה"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="נוצר על ידי",
                    ),
                ),
                (
                    "from_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_from",
                        to="inventory.location",
                        verbose_name="ממיקום",
                    ),
                ),
                (
                    "to_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_to",
                        to="inventory.location",
                        verbose_name="למיקום",
                    ),
                ),
            ],
            options={
                "verbose_name": "העברת מלאי",
                "verbose_name_plural": "העברות מלאי",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="מספר חשבונית"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "טיוטה"),
                            ("confirmed", "מאושר"),
                            ("completed", "הושלם"),
                            ("cancelled", "בוטל"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="סטטוס",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "ממתין לתשלום"),
                            ("partial", "תשלום חלקי"),
                            ("paid", "שולם"),
                            ("refunded", "הוחזר"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="סטטוס תשלום",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name='סכום לפני מע"מ',
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=17,
                        max_digits=5,
                        verbose_name='אחוז מע"מ',
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name='סכום מע"מ',
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="סכום כולל",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="הערות"),
                ),
                (
                    "sale_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="תאריך מכירה"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="נוצר על ידי",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.customer",
                        verbose_name="לקוח",
                    ),
                ),
            ],
            options={
                "verbose_name": "מכירה",
                "verbose_name_plural": "מכירות",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="כמות",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="מחיר יחידה"
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="אחוז הנחה",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="סכום הנחה",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="סכום כולל"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                        verbose_name="מוצר",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.sale",
                        verbose_name="מכירה",
                    ),
                ),
            ],
            options={
                "verbose_name": "פריט חשבונית",
                "verbose_name_plural": "פריטי חשבונית",
            },
        ),
        migrations.CreateModel(
            name="TransferItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="כמות",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="הערות"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                        verbose_name="מוצר",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.inventorytransfer",
                        verbose_name="העברה",
                    ),
                ),
            ],
            options={
                "verbose_name": "פריט העברה",
                "verbose_name_plural": "פריטי העברה",
            },
        ),
    ]
