# Generated by Django 5.2.7 on 2025-10-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("credit_clearing", "סליקה כולל"),
                    ("cash", "מזומן"),
                    ("credit_card", "כרטיס אשראי"),
                    ("bit", "ביט"),
                    ("paypal", "פייפאל"),
                    ("paybox", "פייבוקס"),
                ],
                max_length=30,
                null=True,
                verbose_name="אפשרות תשלום",
            ),
        ),
    ]
