# Generated by Django 5.2.7 on 2025-10-05 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_sale_payment_method"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(
                        default=False, verbose_name="הפעל שליחת מיילים"
                    ),
                ),
                (
                    "email_host",
                    models.CharField(
                        default="smtp.gmail.com",
                        max_length=200,
                        verbose_name="שרת SMTP",
                    ),
                ),
                (
                    "email_port",
                    models.IntegerField(default=587, verbose_name="פורט SMTP"),
                ),
                (
                    "email_use_tls",
                    models.BooleanField(default=True, verbose_name="השתמש ב-TLS"),
                ),
                (
                    "email_use_ssl",
                    models.BooleanField(default=False, verbose_name="השתמש ב-SSL"),
                ),
                (
                    "email_host_user",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="כתובת מייל שולח"
                    ),
                ),
                (
                    "email_host_password",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="סיסמה/App Password"
                    ),
                ),
                (
                    "default_from_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="מייל ברירת מחדל"
                    ),
                ),
                (
                    "daily_report_enabled",
                    models.BooleanField(default=False, verbose_name="הפעל דוח יומי"),
                ),
                (
                    "daily_report_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="מייל לקבלת דוחות"
                    ),
                ),
                (
                    "daily_report_time",
                    models.TimeField(default="19:30", verbose_name="שעת שליחת דוח"),
                ),
                (
                    "alert_email_enabled",
                    models.BooleanField(
                        default=False, verbose_name="הפעל התראות במייל"
                    ),
                ),
                (
                    "alert_email_recipients",
                    models.TextField(
                        blank=True,
                        help_text="הפרד בפסיקים",
                        verbose_name="מיילים לקבלת התראות",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "הגדרות מערכת",
                "verbose_name_plural": "הגדרות מערכת",
            },
        ),
    ]
