# Generated by Django 5.2.7 on 2025-10-04 10:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_customer_inventorytransfer_sale_saleitem_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="שם תבנית")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="תבנית ברירת מחדל"),
                ),
                (
                    "header_text",
                    models.TextField(blank=True, null=True, verbose_name="טקסט כותרת"),
                ),
                (
                    "footer_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="טקסט כותרת תחתונה"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=200, verbose_name="שם החברה"),
                ),
                ("company_address", models.TextField(verbose_name="כתובת החברה")),
                (
                    "company_phone",
                    models.CharField(max_length=20, verbose_name="טלפון החברה"),
                ),
                (
                    "company_email",
                    models.EmailField(max_length=254, verbose_name="אימייל החברה"),
                ),
                (
                    "company_tax_id",
                    models.CharField(max_length=20, verbose_name="ח.פ החברה"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="invoice_logos/",
                        verbose_name="לוגו",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="פעיל")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "תבנית חשבונית",
                "verbose_name_plural": "תבניות חשבוניות",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="עיר"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="country",
            field=models.CharField(
                default="ישראל", max_length=100, verbose_name="מדינה"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="נוצר על ידי",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="credit_limit",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="מגבלת אשראי"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="customer_code",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="קוד לקוח",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="customer_type",
            field=models.CharField(
                choices=[
                    ("individual", "פרטי"),
                    ("business", "עסקי"),
                    ("wholesale", "סיטונאי"),
                ],
                default="individual",
                max_length=20,
                verbose_name="סוג לקוח",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="אחוז הנחה"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="id_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="ת.ז"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_vip",
            field=models.BooleanField(default=False, verbose_name="לקוח VIP"),
        ),
        migrations.AddField(
            model_name="customer",
            name="last_purchase_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="רכישה אחרונה"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="mobile",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="נייד"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="הערות"),
        ),
        migrations.AddField(
            model_name="customer",
            name="payment_terms",
            field=models.CharField(
                default="30 ימים", max_length=100, verbose_name="תנאי תשלום"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="מיקוד"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "נמוכה"),
                    ("medium", "בינונית"),
                    ("high", "גבוהה"),
                    ("vip", "VIP"),
                ],
                default="medium",
                max_length=20,
                verbose_name="עדיפות",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="total_orders",
            field=models.PositiveIntegerField(default=0, verbose_name='סה"כ הזמנות'),
        ),
        migrations.AddField(
            model_name="customer",
            name="total_purchases",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name='סה"כ רכישות'
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="website",
            field=models.URLField(blank=True, null=True, verbose_name="אתר אינטרנט"),
        ),
        migrations.CreateModel(
            name="CustomerAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("birthday", "יום הולדת"),
                            ("anniversary", "יום השנה"),
                            ("follow_up", "מעקב נדרש"),
                            ("payment_overdue", "תשלום באיחור"),
                            ("credit_limit", "מגבלת אשראי"),
                            ("inactive", "לקוח לא פעיל"),
                            ("high_value", "רכישה גבוהה"),
                        ],
                        max_length=20,
                        verbose_name="סוג התראה",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="כותרת")),
                ("message", models.TextField(verbose_name="הודעה")),
                ("is_read", models.BooleanField(default=False, verbose_name="נקרא")),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="נפתר"),
                ),
                (
                    "alert_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="תאריך התראה"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="תאריך פתרון"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_alerts",
                        to="inventory.customer",
                        verbose_name="לקוח",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="נפתר על ידי",
                    ),
                ),
            ],
            options={
                "verbose_name": "התראת לקוח",
                "verbose_name_plural": "התראות לקוחות",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("general", "כללי"),
                            ("call", "שיחה"),
                            ("email", "אימייל"),
                            ("meeting", "פגישה"),
                            ("complaint", "תלונה"),
                            ("compliment", "מחמאה"),
                            ("follow_up", "מעקב"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="סוג הערה",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="כותרת")),
                ("content", models.TextField(verbose_name="תוכן")),
                (
                    "is_important",
                    models.BooleanField(default=False, verbose_name="חשוב"),
                ),
                (
                    "follow_up_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="תאריך מעקב"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="נוצר על ידי",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_notes",
                        to="inventory.customer",
                        verbose_name="לקוח",
                    ),
                ),
            ],
            options={
                "verbose_name": "הערת לקוח",
                "verbose_name_plural": "הערות לקוחות",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerSaleHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sale_date", models.DateTimeField(verbose_name="תאריך מכירה")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="סכום כולל"
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "ממתין לתשלום"),
                            ("partial", "תשלום חלקי"),
                            ("paid", "שולם"),
                            ("refunded", "הוחזר"),
                        ],
                        max_length=20,
                        verbose_name="סטטוס תשלום",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_history",
                        to="inventory.customer",
                        verbose_name="לקוח",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.sale",
                        verbose_name="מכירה",
                    ),
                ),
            ],
            options={
                "verbose_name": "היסטוריית מכירות",
                "verbose_name_plural": "היסטוריית מכירות",
                "ordering": ["-sale_date"],
            },
        ),
    ]
