# Generated by Django 5.2.7 on 2025-10-04 10:10

from django.db import migrations, models
from django.conf import settings
from django.utils import timezone
from django.db import models as models_deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_invoicetemplate_customer_city_customer_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('warehouse', 'מחסן'), ('store', 'חנות'), ('office', 'משרד'), ('factory', 'מפעל'), ('other', 'אחר')], default='warehouse', max_length=20, verbose_name='סוג מיקום'),
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='עיר'),
        ),
        migrations.AddField(
            model_name='location',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='מיקוד'),
        ),
        migrations.AddField(
            model_name='location',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='טלפון'),
        ),
        migrations.AddField(
            model_name='location',
            name='email',
            field=models.EmailField(blank=True, null=True, verbose_name='אימייל'),
        ),
        migrations.AddField(
            model_name='location',
            name='manager_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='שם מנהל'),
        ),
        migrations.AddField(
            model_name='location',
            name='capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='קיבולת (יחידות)'),
        ),
        migrations.AddField(
            model_name='location',
            name='is_main_warehouse',
            field=models.BooleanField(default=False, verbose_name='מחסן ראשי'),
        ),
        migrations.AddField(
            model_name='location',
            name='is_main_store',
            field=models.BooleanField(default=False, verbose_name='חנות ראשית'),
        ),
        migrations.AddField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='LocationAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_stock', 'מלאי נמוך'), ('out_of_stock', 'אזל מהמלאי'), ('overstock', 'מלאי עודף'), ('capacity_full', 'קיבולת מלאה'), ('capacity_almost_full', 'קיבולת כמעט מלאה'), ('expired_products', 'מוצרים פגי תוקף'), ('near_expiry', 'מוצרים קרובים לפג תוקף'), ('maintenance_required', 'נדרש תחזוקה'), ('security_breach', 'הפרת אבטחה'), ('temperature_issue', 'בעיית טמפרטורה'), ('other', 'אחר')], max_length=30, verbose_name='סוג התראה')),
                ('priority', models.CharField(choices=[('low', 'נמוכה'), ('medium', 'בינונית'), ('high', 'גבוהה'), ('critical', 'קריטית')], default='medium', max_length=20, verbose_name='עדיפות')),
                ('title', models.CharField(max_length=200, verbose_name='כותרת')),
                ('message', models.TextField(verbose_name='הודעה')),
                ('is_read', models.BooleanField(default=False, verbose_name='נקרא')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='נפתר')),
                ('alert_date', models.DateTimeField(default=timezone.now, verbose_name='תאריך התראה')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='תאריך פתרון')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=models_deletion.CASCADE, related_name='location_alerts', to='inventory.location', verbose_name='מיקום')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=models_deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='נפתר על ידי')),
            ],
            options={
                'verbose_name': 'התראת מיקום',
                'verbose_name_plural': 'התראות מיקום',
                'ordering': ['-created_at'],
            },
        ),
    ]
