# Generated by Django 5.2.7 on 2025-10-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_auto_20251004_1310"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={
                "ordering": ["name"],
                "verbose_name": "מיקום",
                "verbose_name_plural": "מיקומים",
            },
        ),
        migrations.AlterField(
            model_name="location",
            name="address",
            field=models.TextField(blank=True, verbose_name="כתובת"),
        ),
        migrations.AlterField(
            model_name="location",
            name="description",
            field=models.TextField(blank=True, verbose_name="תיאור"),
        ),
        migrations.AlterField(
            model_name="location",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="פעיל"),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="שם מיקום"
            ),
        ),
    ]
