# Generated by Django 5.2.7 on 2025-10-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_add_alert_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsettings",
            name="daily_report_time",
            field=models.TimeField(default="19:30:00", verbose_name="שעת שליחת דוח"),
        ),
    ]
