# Generated by Django 5.2.7 on 2025-10-04 13:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_alter_location_options_alter_location_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="החנות בה בוצעה המכירה",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.location",
                verbose_name="מיקום מכירה",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="מיקום ברירת מחדל",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.location",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(
                default=0,
                help_text='סה"כ מלאי בכל המיקומים',
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.CreateModel(
            name="ProductLocationStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="כמות במלאי",
                    ),
                ),
                (
                    "min_quantity",
                    models.IntegerField(
                        default=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="כמות מינימלית",
                    ),
                ),
                (
                    "last_restocked",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="תאריך אספקה אחרון"
                    ),
                ),
                (
                    "last_sold",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="תאריך מכירה אחרון"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_stocks",
                        to="inventory.location",
                        verbose_name="מיקום",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_stocks",
                        to="inventory.product",
                        verbose_name="מוצר",
                    ),
                ),
            ],
            options={
                "verbose_name": "מלאי מוצר במיקום",
                "verbose_name_plural": "מלאי מוצרים במיקומים",
                "ordering": ["product__name", "location__name"],
                "unique_together": {("product", "location")},
            },
        ),
    ]
