# Generated by Django 5.2.7 on 2025-10-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_sale_location_alter_product_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="location_type",
            field=models.CharField(
                choices=[("store", "חנות"), ("warehouse", "מחסן")],
                default="store",
                max_length=20,
                verbose_name="סוג מיקום",
            ),
        ),
    ]
