# Generated by Django 5.2.7 on 2025-10-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_alter_location_location_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2, default=18, max_digits=5, verbose_name='אחוז מע"מ'
            ),
        ),
    ]
