# Generated by Django 5.2.7 on 2025-10-04 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_alter_sale_tax_rate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="digital_signature",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="חתימה דיגיטלית"
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="is_archived",
            field=models.BooleanField(default=False, verbose_name="בארכיון"),
        ),
        migrations.AddField(
            model_name="sale",
            name="qr_code",
            field=models.TextField(blank=True, verbose_name="QR Code"),
        ),
        migrations.AddField(
            model_name="sale",
            name="requires_tax_authority_number",
            field=models.BooleanField(default=False, verbose_name="דורש מספר הקצאה"),
        ),
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=200, verbose_name="שם החברה"),
                ),
                (
                    "business_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="מספר עוסק מורשה"
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(blank=True, max_length=20, verbose_name="ח.פ"),
                ),
                ("address", models.CharField(max_length=200, verbose_name="כתובת")),
                ("city", models.CharField(max_length=100, verbose_name="עיר")),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=10, verbose_name="מיקוד"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="טלפון")),
                ("email", models.EmailField(max_length=254, verbose_name="אימייל")),
                ("website", models.URLField(blank=True, verbose_name="אתר אינטרנט")),
                (
                    "invoice_prefix",
                    models.CharField(
                        default="INV", max_length=10, verbose_name="קידומת חשבונית"
                    ),
                ),
                (
                    "current_invoice_number",
                    models.PositiveIntegerField(
                        default=1, verbose_name="מספר חשבונית נוכחי"
                    ),
                ),
                (
                    "tax_authority_allocation_number",
                    models.CharField(
                        blank=True,
                        help_text="נדרש לחשבוניות מעל 20,000 ₪",
                        max_length=50,
                        verbose_name="מספר הקצאה מרשות המיסים",
                    ),
                ),
                (
                    "digital_signature_key",
                    models.TextField(blank=True, verbose_name="מפתח חתימה דיגיטלית"),
                ),
                (
                    "signature_certificate",
                    models.TextField(blank=True, verbose_name="תעודת חתימה"),
                ),
                (
                    "default_tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=18,
                        max_digits=5,
                        verbose_name='אחוז מע"מ ברירת מחדל',
                    ),
                ),
                (
                    "archive_years",
                    models.PositiveIntegerField(
                        default=7, verbose_name="שנות שמירה (ברירת מחדל 7)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="פעיל")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="עודכן על ידי",
                    ),
                ),
            ],
            options={
                "verbose_name": "הגדרות חברה",
                "verbose_name_plural": "הגדרות חברה",
            },
        ),
        migrations.CreateModel(
            name="InvoiceArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_data", models.JSONField(verbose_name="נתוני חשבונית מלאים")),
                ("invoice_html", models.TextField(verbose_name="HTML של החשבונית")),
                (
                    "invoice_pdf",
                    models.BinaryField(
                        blank=True, null=True, verbose_name="PDF של החשבונית"
                    ),
                ),
                (
                    "digital_signature",
                    models.CharField(max_length=255, verbose_name="חתימה דיגיטלית"),
                ),
                (
                    "signature_timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="זמן חתימה"),
                ),
                ("qr_code_data", models.TextField(verbose_name="נתוני QR Code")),
                (
                    "archived_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="תאריך ארכוב"),
                ),
                ("delete_after", models.DateField(verbose_name="מחיקה לאחר")),
                (
                    "is_encrypted",
                    models.BooleanField(default=False, verbose_name="מוצפן"),
                ),
                (
                    "encryption_method",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="שיטת הצפנה"
                    ),
                ),
                (
                    "sale",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.sale",
                        verbose_name="חשבונית",
                    ),
                ),
            ],
            options={
                "verbose_name": "ארכיון חשבונית",
                "verbose_name_plural": "ארכיון חשבוניות",
                "ordering": ["-archived_at"],
                "indexes": [
                    models.Index(
                        fields=["delete_after"], name="inventory_i_delete__93b2f1_idx"
                    ),
                    models.Index(
                        fields=["-archived_at"], name="inventory_i_archive_6d19e8_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InvoiceAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "יצירה"),
                            ("view", "צפייה"),
                            ("edit", "עריכה"),
                            ("delete", "מחיקה"),
                            ("print", "הדפסה"),
                            ("email", "שליחה באימייל"),
                            ("export", "ייצוא"),
                            ("cancel", "ביטול"),
                        ],
                        max_length=20,
                        verbose_name="פעולה",
                    ),
                ),
                (
                    "performed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="זמן ביצוע"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="כתובת IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="User Agent"
                    ),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True, null=True, verbose_name="ערכים קודמים"
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(blank=True, null=True, verbose_name="ערכים חדשים"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="הערות")),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="בוצע על ידי",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="inventory.sale",
                        verbose_name="חשבונית",
                    ),
                ),
            ],
            options={
                "verbose_name": "רישום ביקורת",
                "verbose_name_plural": "רישומי ביקורת",
                "ordering": ["-performed_at"],
                "indexes": [
                    models.Index(
                        fields=["-performed_at"], name="inventory_i_perform_72fdbb_idx"
                    ),
                    models.Index(
                        fields=["sale", "-performed_at"],
                        name="inventory_i_sale_id_5db9a8_idx",
                    ),
                ],
            },
        ),
    ]
